import React,{useState} from 'react';
import {Leaf,ArrowUpRight,Play,ShieldCheck,Download,ArrowLeft} from 'lucide-react';
import {api} from './api';
export default function Auth({onAuthenticated,PlantArt}) {
 const [mode,setMode]=useState('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState(null),[privacy,setPrivacy]=useState(false);
 async function submit(e) {
  e.preventDefault();setError('');setBusy(true);
  const body=Object.fromEntries(new FormData(e.currentTarget));
  try {const result=await api('/auth/'+mode,{method:'POST',body:JSON.stringify(body)});if(result.recovery_code)setReceipt(result);else onAuthenticated(result);}catch(e){setError(e.message);}finally{setBusy(false);}
 }
 async function demo(){setBusy(true);setError('');try{onAuthenticated(await api('/auth/demo',{method:'POST'}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 function saveRecovery(){const file=new Blob([`Cloud-Connected Smart Plant Care\nPrivate recovery code: ${receipt.recovery_code}\nKeep this file private. This code can reset your password and is shown only once.\n`],{type:'text/plain'});const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download='plant-care-private-recovery.txt';a.click();URL.revokeObjectURL(url);}
 return <div className="login-shell"><div className="login-story"><div className="brand"><Leaf/> Plant Care<span>CLOUD-CONNECTED</span></div><div className="login-copy"><span className="eyebrow">CLOUD COMPUTING · VIRTUAL IoT</span><h1>Understand.<br/>Monitor.<br/>Help it grow.</h1><p>A cloud-connected smart plant care and watering system. Explore live sensor trends and automatic watering—no hardware needed.</p><PlantArt large/><div className="login-foot"><ShieldCheck size={19}/> Private gardens. Shared curiosity.</div></div></div><main className="login-form">
 {receipt?<><span className="eyebrow">YOUR GARDEN IS READY</span><h2>Keep your recovery code.</h2><p>This is the only time it is shown. It lets you reset your password without an email service.</p><code className="recovery-code">{receipt.recovery_code}</code><button className="outline" onClick={saveRecovery}><Download size={17}/> Download recovery code</button><button className="primary" style={{marginTop:14}} onClick={()=>onAuthenticated(receipt)}>I’ve saved it · Open my garden <ArrowUpRight size={18}/></button></>:<>
 <span className="eyebrow">CLOUD-CONNECTED SMART PLANT CARE</span><h2>{mode==='register'?'Create your garden.':mode==='recover'?'Recover your account.':'See how your garden grows.'}</h2><p>{mode==='register'?'Your own plants, saved history, and a built-in simulator.':mode==='recover'?'Use the private recovery code you saved at signup.':'Try the interactive demo or sign in to your own garden.'}</p>
 {mode==='login'&&<><button className="demo-button" disabled={busy} onClick={demo}><Play size={18}/> Try interactive demo <span>No signup needed</span></button><div className="auth-divider">or sign in to save your garden</div></>}
 <form onSubmit={submit} key={mode}>
 {mode==='register'&&<label>Your name<input name="name" autoComplete="name" minLength={2} maxLength={60} required/></label>}
 <label>Email address<input name="email" type="email" autoComplete="username" required maxLength={150}/></label>
 {mode==='recover'&&<label>Recovery code<input name="recovery_code" autoComplete="off" required minLength={20} maxLength={128}/></label>}
 <label>{mode==='recover'?'New password':'Password'}<input aria-label={mode==='recover'?'New password':'Password'} name="password" type="password" required minLength={10} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'}/>{mode!=='login'&&<small>Use at least 10 characters.</small>}</label>
 <button className="primary" disabled={busy}>{busy?'Please wait…':mode==='register'?'Create my garden':mode==='recover'?'Reset password':'Sign in'}<ArrowUpRight size={18}/></button>
 </form>{error&&<p className="error" role="alert">{error}</p>}
 <div className="auth-links">{mode==='login'?<><button onClick={()=>{setMode('register');setError('');}}>New here? Create an account</button><button onClick={()=>{setMode('recover');setError('');}}>Forgot password?</button></>:<button onClick={()=>{setMode('login');setError('');}}><ArrowLeft size={14}/> Back to sign in</button>}</div>
 <div className="login-note">Demo gardens expire after one hour. Registered gardens stay saved. All sensor readings are simulated.<br/><button className="privacy-link" onClick={()=>setPrivacy(true)}>Privacy & data use</button></div>
 </>}<small>SMART PLANT CARE & WATERING SYSTEM</small>
 </main>{privacy&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Privacy and data use"><button className="close" aria-label="Close privacy notice" onClick={()=>setPrivacy(false)}>×</button><h2>Your data, plainly.</h2><p>Accounts store your name, email, password hash and simulated garden records. Your email is a sign-in identifier; this app does not verify it or send email. Do not enter sensitive information.</p><p>Raw readings are retained for seven days; completed watering events and resolved alerts for 90 days. Temporary demo accounts expire after one hour and are cleaned up periodically. You can permanently delete a registered account from Settings.</p><p>A necessary, HttpOnly session cookie keeps you signed in for one hour. There are no advertising trackers. Hosting providers process application traffic; fonts may load from Google Fonts.</p><button className="primary" onClick={()=>setPrivacy(false)}>Understood</button></section></div>}</div>;
}
