const {chromium}=require('playwright');
const fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'../screenshots');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');
 await page.getByRole('button',{name:/Try interactive demo/}).waitFor();
 await page.screenshot({path:path.join(out,'00_Login.png'),fullPage:true});
 await page.getByRole('button',{name:/Try interactive demo/}).click();
 await page.getByRole('heading',{name:'A good day to grow.'}).waitFor();
 await page.getByText('Your virtual sensor is running',{exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'01_Dashboard.png'),fullPage:true});
 await page.reload();
 await page.getByText('Your virtual sensor is running',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Simulate dry soil',exact:true}).click();
 await page.getByText('Pump is watering',{exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'06_Automatic_Watering.png'),fullPage:true});
 await page.getByRole('button',{name:'Stop watering',exact:true}).click();
 await page.getByText('Pump is resting',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Analytics',exact:true}).click();
 await page.getByText('Average moisture',{exact:true}).waitFor();
 await page.getByLabel('Chart metric').selectOption('temperature');
 await page.screenshot({path:path.join(out,'02_Analytics.png'),fullPage:true});
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByLabel('Moisture threshold',{exact:true}).fill('32');
 await page.getByRole('button',{name:'Save care settings'}).click();
 await page.getByRole('status').filter({hasText:'Care settings saved'}).waitFor();
 await page.screenshot({path:path.join(out,'03_Care_Settings.png'),fullPage:true});
 await page.getByRole('button',{name:/^Alerts/}).click();
 await page.getByRole('button',{name:'Acknowledge'}).first().click();
 await page.getByRole('status').filter({hasText:'Alert acknowledged'}).waitFor();
 await page.screenshot({path:path.join(out,'04_Alerts.png'),fullPage:true});
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'05_Mobile.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(overflow)throw Error('Mobile overflow');
 await page.setViewportSize({width:1440,height:1100});
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'New here? Create an account'}).click();
 const email='browser-'+Date.now()+'@example.com';
 await page.getByLabel('Your name',{exact:true}).fill('Demo Gardener');
 await page.getByLabel('Email address',{exact:true}).fill(email);
 await page.getByLabel('Password',{exact:true}).fill('Browser-test-password-123');
 await page.getByRole('button',{name:'Create my garden',exact:true}).click();
 await page.getByRole('heading',{name:'Keep your recovery code.'}).waitFor();
 const recovery=await page.locator('.recovery-code').innerText();
 await page.getByRole('button',{name:/I’ve saved it/}).click();
 await page.getByText('Your virtual sensor is running',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByLabel('Automatic watering',{exact:true}).uncheck();
 await page.getByRole('button',{name:'Save care settings'}).click();
 await page.getByRole('status').filter({hasText:'Care settings saved'}).waitFor();
 await page.getByRole('button',{name:'Simulate dry soil',exact:true}).click();
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.getByRole('button',{name:/Water now/}).click();
 await page.getByText('Pump is watering',{exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'07_Manual_Watering.png'),fullPage:true});
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 await page.getByText('Your virtual sensor is paused',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'Forgot password?'}).click();
 await page.getByLabel('Email address',{exact:true}).fill(email);
 await page.getByLabel('Recovery code',{exact:true}).fill(recovery);
 await page.getByLabel('New password',{exact:true}).fill('Browser-reset-password-456');
 await page.getByRole('button',{name:'Reset password',exact:true}).click();
 await page.getByRole('heading',{name:'Keep your recovery code.'}).waitFor();
 await page.getByRole('button',{name:/I’ve saved it/}).click();
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByRole('button',{name:'Delete my account',exact:true}).click();
 await page.getByLabel('Confirm your password',{exact:true}).fill('Browser-reset-password-456');
 await page.getByRole('button',{name:'Permanently delete account',exact:true}).click();
 await page.getByRole('button',{name:/Try interactive demo/}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));
 const evidence={guest_demo:'pass',session_reload:'pass',automatic_watering:'pass',manual_watering:'pass',pause_and_stop:'pass',settings:'pass',charts:'pass',alerts:'pass',mobile_overflow:false,registration:'pass',password_recovery:'pass',account_deletion:'pass',console_errors:errors};
 fs.writeFileSync(path.join(root,'reports','browser-actions.json'),JSON.stringify(evidence,null,2));
 console.log(JSON.stringify(evidence,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});

