const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const out=path.join(root,'screenshots');fs.mkdirSync(out,{recursive:true});
const creds=JSON.parse(fs.readFileSync(path.join(root,'.demo-credentials.json'),'utf8'));
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000',{waitUntil:'networkidle'});
 await page.screenshot({path:path.join(out,'00_Login.png'),fullPage:true});
 await page.getByLabel('Email address').fill(creds.email);
 await page.getByLabel('Password',{exact:true}).fill(creds.password);
 await page.getByRole('button',{name:'Open my garden'}).click();
 await page.getByRole('heading',{name:'A good day to grow.'}).waitFor();
 await page.getByRole('heading',{name:'Monstera Deliciosa',exact:true}).first().waitFor();
 await page.screenshot({path:path.join(out,'01_Dashboard.png'),fullPage:true});
 await page.getByRole('button',{name:'Analytics',exact:true}).click();
 await page.getByText('Average moisture',{exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'02_Analytics.png'),fullPage:true});
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByLabel('Moisture threshold',{exact:true}).fill('32');
 await page.getByRole('button',{name:'Save care settings'}).click();
 await page.getByRole('status').filter({hasText:'Care settings saved'}).waitFor();
 await page.screenshot({path:path.join(out,'03_Care_Settings.png'),fullPage:true});
 await page.getByLabel('Moisture threshold',{exact:true}).fill('30');
 await page.getByRole('button',{name:'Save care settings'}).click();
 await page.getByRole('button',{name:/^Alerts/}).click();
 await page.screenshot({path:path.join(out,'04_Alerts.png'),fullPage:true});
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'05_Mobile.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(overflow||errors.length)throw new Error(JSON.stringify({overflow,errors}));
 console.log(JSON.stringify({login:'pass',dashboard:'pass',analytics:'pass',settings:'pass',alerts:'pass',mobile_overflow:overflow,console_errors:errors},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
